import { Link, router } from '@inertiajs/react';
import { Eye, Pencil, RotateCcw, Trash2, UserRound } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Tooltip } from '@/components/ui/tooltip';
import type { Customer, Paginated } from '@/types';
import { shortDate } from '@/lib/format';

const actionButton = 'flex size-8 items-center justify-center rounded-md text-ink-3 transition-colors hover:bg-surface-3 hover:text-ink [&_svg]:size-4';

export function CustomersTable({ customers, archived, canUpdate, canArchive }: { customers: Paginated<Customer>; archived?: boolean; canUpdate: boolean; canArchive: boolean }) {
    return <div className="overflow-x-auto"><table className="w-full min-w-[860px] border-collapse text-left"><thead className="bg-surface-2"><tr className="border-b border-line"><th className="h-10 w-12 px-3.5 text-xs font-semibold text-ink-2">#</th><th className="h-10 px-3 text-xs font-semibold text-ink-2">Customer</th><th className="h-10 px-3 text-xs font-semibold text-ink-2">Status</th><th className="h-10 px-3 text-xs font-semibold text-ink-2">Owner</th><th className="h-10 px-3 text-xs font-semibold text-ink-2">Last contact</th><th className="h-10 px-3 text-xs font-semibold text-ink-2">Added</th><th className="h-10 px-3.5 text-right text-xs font-semibold text-ink-2">Actions</th></tr></thead><tbody>{customers.data.length === 0 ? <tr><td colSpan={7} className="px-4 py-14 text-center text-xs text-ink-3">No customers found.</td></tr> : customers.data.map((customer, index) => <tr key={customer.id} className="border-b border-line/70 transition-colors last:border-b-0 hover:bg-surface-2"><td className="num h-[60px] px-3.5 text-xs font-medium text-ink-2">{(customers.from ?? 1) + index}</td><td className="px-3"><Link href={`/customers/${customer.id}`} className="block max-w-[260px] truncate text-xs font-medium text-ink hover:text-brand">{customer.name}</Link><p className="max-w-[260px] truncate text-2xs text-ink-3">{customer.business ?? customer.email ?? customer.phone ?? 'No contact details'}</p></td><td className="px-3"><Badge tone={customer.status === 'active' ? 'ok' : 'neutral'} size="sm" dot>{customer.status === 'active' ? 'Active' : 'Inactive'}</Badge></td><td className="px-3">{customer.owner ? <span className="inline-flex items-center gap-1.5 text-xs text-ink-2"><UserRound className="size-3.5 text-ink-3" />{customer.owner.name}</span> : <span className="text-2xs text-ink-3">Unassigned</span>}</td><td className="num px-3 text-2xs text-ink-2">{shortDate(customer.last_contacted_at)}</td><td className="num px-3 text-2xs text-ink-3">{shortDate(customer.created_at)}</td><td className="px-3.5"><div className="flex items-center justify-end gap-0.5"><Tooltip label="View"><Link href={`/customers/${customer.id}`} className={actionButton}><Eye /></Link></Tooltip>{!archived && canUpdate && <Tooltip label="Edit"><Link href={`/customers/${customer.id}/edit`} className={`${actionButton} text-warn hover:bg-warn-wash hover:text-warn`}><Pencil /></Link></Tooltip>}{archived && canArchive ? <Tooltip label="Restore"><button type="button" onClick={() => router.patch(`/customers/${customer.id}/restore`)} className={`${actionButton} text-ok hover:bg-ok-wash hover:text-ok`}><RotateCcw /></button></Tooltip> : !archived && canArchive ? <Tooltip label="Archive"><button type="button" onClick={() => router.delete(`/customers/${customer.id}`)} className={`${actionButton} text-bad hover:bg-bad-wash hover:text-bad`}><Trash2 /></button></Tooltip> : null}</div></td></tr>)}</tbody></table></div>;
}

export function CustomersGrid({ customers, archived, canUpdate, canArchive }: { customers: Paginated<Customer>; archived?: boolean; canUpdate: boolean; canArchive: boolean }) {
    return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{customers.data.map((customer) => <Card key={customer.id} className="p-4 transition-shadow duration-200 hover:shadow-pop"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Link href={`/customers/${customer.id}`} className="block truncate text-sm font-semibold text-ink hover:text-brand">{customer.name}</Link><p className="mt-0.5 truncate text-2xs text-ink-3">{customer.business ?? customer.email ?? 'No company added'}</p></div><Badge tone={customer.status === 'active' ? 'ok' : 'neutral'} size="sm" dot>{customer.status === 'active' ? 'Active' : 'Inactive'}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-line pt-3"><div><p className="text-2xs text-ink-3">Owner</p><p className="mt-0.5 truncate text-xs text-ink-2">{customer.owner?.name ?? 'Unassigned'}</p></div><div><p className="text-2xs text-ink-3">Last contact</p><p className="num mt-0.5 truncate text-xs text-ink-2">{shortDate(customer.last_contacted_at)}</p></div></div><div className="mt-3 flex items-center justify-between border-t border-line pt-3"><span className="num text-2xs text-ink-3">{shortDate(customer.created_at)}</span><div className="flex items-center gap-0.5"><Tooltip label="View"><Link href={`/customers/${customer.id}`} className={actionButton}><Eye /></Link></Tooltip>{!archived && canUpdate && <Tooltip label="Edit"><Link href={`/customers/${customer.id}/edit`} className={`${actionButton} text-warn hover:bg-warn-wash hover:text-warn`}><Pencil /></Link></Tooltip>}{archived && canArchive ? <Tooltip label="Restore"><button type="button" onClick={() => router.patch(`/customers/${customer.id}/restore`)} className={`${actionButton} text-ok hover:bg-ok-wash hover:text-ok`}><RotateCcw /></button></Tooltip> : !archived && canArchive ? <Tooltip label="Archive"><button type="button" onClick={() => router.delete(`/customers/${customer.id}`)} className={`${actionButton} text-bad hover:bg-bad-wash hover:text-bad`}><Trash2 /></button></Tooltip> : null}</div></div></Card>)}{customers.data.length === 0 && <Card className="col-span-full p-12 text-center text-xs text-ink-3">No customers found.</Card>}</div>;
}
