import { Head, Link, router } from '@inertiajs/react';
import { ArchiveRestore, ArrowLeft, Eye } from 'lucide-react';
import { PageHeader } from '@/components/page-header';
import { Pagination } from '@/components/pagination';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';
import type { Paginated, Subscription } from '@/types';

export default function ArchivedSubscriptions({ subscriptions }: { subscriptions: Paginated<Subscription> }) { return <AppLayout><Head title="Archived subscriptions" /><PageHeader title="Archived subscriptions" actions={<Link href="/subscriptions"><Button variant="secondary"><ArrowLeft /> Back to Subscriptions</Button></Link>} /><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-line bg-surface-2 text-xs uppercase tracking-wider text-ink-3"><tr><th className="px-4 py-3">Plan / instance</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Archived</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-line">{subscriptions.data.map((subscription) => <tr key={subscription.id}><td className="px-4 py-3 font-semibold text-ink">{subscription.plan?.name}<div className="text-xs font-normal text-ink-3">{subscription.application_instance?.name}</div></td><td className="px-4 py-3 text-ink-2">{subscription.application_instance?.customer?.business || subscription.application_instance?.customer?.name}</td><td className="px-4 py-3"><Badge tone="neutral" size="sm">Archived</Badge></td><td className="px-4 py-3 text-ink-3">{subscription.deleted_at ? new Date(subscription.deleted_at).toLocaleDateString() : '—'}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Link href={`/subscriptions/${subscription.id}`}><Button variant="ghost" size="icon" aria-label="View subscription"><Eye /></Button></Link><Button variant="ghost" size="icon" aria-label="Restore subscription" onClick={() => router.patch(`/subscriptions/${subscription.id}/restore`)}><ArchiveRestore /></Button></div></td></tr>)}</tbody></table></div><Pagination meta={subscriptions} perPage={subscriptions.per_page} /></Card></AppLayout>; }
