import { Head, Link, router } from '@inertiajs/react';
import { Archive, ArrowLeft, CalendarDays, ExternalLink, Pencil, Server, RotateCcw } from 'lucide-react';
import { PageHeader } from '@/components/page-header';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardBody, CardHeader } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';
import type { Activity, ApplicationInstance } from '@/types';

const tone: Record<string, 'ok' | 'warn' | 'bad' | 'neutral'> = { active: 'ok', planned: 'warn', paused: 'bad', retired: 'neutral' };
export default function ApplicationInstanceShow({ instance, activities, can }: { instance: ApplicationInstance; activities: Activity[]; can: { update: boolean; archive: boolean; create_follow_up: boolean } }) {
    return <AppLayout><Head title={instance.name} /><PageHeader title={instance.name} description={`${instance.customer?.business || instance.customer?.name || 'Customer'} · ${instance.product?.name || 'Product'}`} actions={<div className="flex gap-2"><Link href="/instances"><Button variant="secondary"><ArrowLeft /> Back to Instances</Button></Link>{can.update && <Link href={`/instances/${instance.id}/edit`}><Button variant="secondary"><Pencil /> Edit</Button></Link>}{instance.deleted_at ? <Button onClick={() => router.patch(`/instances/${instance.id}/restore`)}><RotateCcw /> Restore</Button> : can.archive && <Button variant="secondary" onClick={() => router.delete(`/instances/${instance.id}`)}><Archive /> Archive</Button>}</div>} />
        <div className="grid gap-4 lg:grid-cols-[minmax(0,1.4fr)_minmax(280px,.8fr)]"><div className="space-y-4"><Card><CardHeader title="Deployment overview" action={<Badge tone={tone[instance.status] ?? 'neutral'}>{instance.status_label ?? instance.status}</Badge>} /><CardBody className="grid gap-4 sm:grid-cols-2"><div><div className="text-xs uppercase tracking-wider text-ink-3">Environment</div><div className="mt-1 font-medium capitalize text-ink">{instance.environment_label ?? instance.environment}</div></div><div><div className="text-xs uppercase tracking-wider text-ink-3">Version</div><div className="mt-1 font-medium text-ink">{instance.version || 'Not specified'}</div></div><div><div className="text-xs uppercase tracking-wider text-ink-3">Deployment URL</div>{instance.deployment_url ? <a className="mt-1 inline-flex items-center gap-1 text-brand hover:underline" href={instance.deployment_url} target="_blank" rel="noreferrer">Open deployment <ExternalLink className="size-3.5" /></a> : <div className="mt-1 text-ink-3">Not specified</div>}</div><div><div className="text-xs uppercase tracking-wider text-ink-3">Server / host</div><div className="mt-1 text-ink-2">{instance.server_name || 'Not specified'}</div></div><div><div className="text-xs uppercase tracking-wider text-ink-3">Deployed on</div><div className="mt-1 flex items-center gap-1 text-ink-2">{instance.deployed_at ? <><CalendarDays className="size-4 text-ink-3" />{new Date(instance.deployed_at).toLocaleDateString()}</> : 'Not specified'}</div></div><div><div className="text-xs uppercase tracking-wider text-ink-3">Owner</div><div className="mt-1 text-ink-2">{instance.owner?.name || 'Unassigned'}</div></div></CardBody></Card><ActivityHistory activities={activities} /></div><div className="space-y-4"><Card><CardHeader title="Operational context" /><CardBody className="space-y-3"><Link href={`/customers/${instance.customer_id}`} className="flex items-center gap-3 rounded-lg p-2 hover:bg-surface-2"><div className="flex size-9 items-center justify-center rounded-lg bg-brand/10 text-brand"><Server className="size-4" /></div><div><div className="text-xs text-ink-3">Customer</div><div className="font-medium text-ink">{instance.customer?.business || instance.customer?.name}</div></div></Link><Link href={`/products/${instance.product_id}`} className="flex items-center gap-3 rounded-lg p-2 hover:bg-surface-2"><div className="flex size-9 items-center justify-center rounded-lg bg-brand/10 text-brand">{instance.product?.code?.slice(0, 2) || 'PR'}</div><div><div className="text-xs text-ink-3">Product</div><div className="font-medium text-ink">{instance.product?.name}</div></div></Link></CardBody></Card>{instance.notes && <Card><CardHeader title="Notes" /><CardBody><p className="whitespace-pre-wrap text-sm text-ink-2">{instance.notes}</p></CardBody></Card>}</div></div>
    </AppLayout>;
}

function ActivityHistory({ activities }: { activities: Activity[] }) {
    return <Card><CardHeader title="Activity" meta={`${activities.length}`} /><CardBody>{activities.length ? <div className="space-y-3">{activities.map((activity) => <div key={activity.id} className="border-l-2 border-brand/30 pl-3"><div className="text-sm text-ink">{activity.description || activity.event}</div><div className="mt-0.5 text-xs text-ink-3">{activity.user?.name || 'System'} · {new Date(activity.created_at).toLocaleString()}</div></div>)}</div> : <p className="text-sm text-ink-3">No activity recorded yet.</p>}</CardBody></Card>;
}
