<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CalendarController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\DataExportController;
use App\Http\Controllers\DataImportController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerContactController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\LeadSourceController;
use App\Http\Controllers\LeadStatusController;
use App\Http\Controllers\FollowUpController;
use App\Http\Controllers\DealController;
use App\Http\Controllers\DealStageController;
use App\Http\Controllers\LoginHistoryController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ThemeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ApplicationInstanceController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\SupportTicketController;
use App\Http\Controllers\WorkTaskController;
use App\Http\Controllers\SearchController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard')->name('home');

Route::middleware('auth')->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::get('calendar', CalendarController::class)->name('calendar.index');
    Route::get('reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('reports/export', [ReportController::class, 'export'])->name('reports.export');
    Route::get('imports', [DataImportController::class, 'index'])->name('imports.index');
    Route::get('imports/templates/{type}', [DataImportController::class, 'template'])->name('imports.template');
    Route::post('imports/customers', [DataImportController::class, 'customers'])->name('imports.customers');
    Route::post('imports/leads', [DataImportController::class, 'leads'])->name('imports.leads');
    Route::post('imports/tasks', [DataImportController::class, 'tasks'])->name('imports.tasks');
    Route::get('activity', ActivityController::class)->name('activity.index');
    Route::get('search', SearchController::class)->name('search');

    Route::get('profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::post('profile', [ProfileController::class, 'update'])->name('profile.update.upload');
    Route::put('profile/password', [ProfileController::class, 'updatePassword'])->name('profile.password');
    Route::patch('theme', [ThemeController::class, 'update'])->name('theme.update');

    Route::get('users', [UserController::class, 'index'])->name('users.index');
    Route::get('products', [ProductController::class, 'index'])->name('products.index');
    Route::get('products/archived', [ProductController::class, 'archived'])->name('products.archived');
    Route::get('products/export', [ProductController::class, 'export'])->name('products.export');
    Route::get('products/create', [ProductController::class, 'create'])->name('products.create');
    Route::post('products', [ProductController::class, 'store'])->name('products.store');
    Route::post('products/import', [ProductController::class, 'import'])->name('products.import');
    Route::get('products/{product}', [ProductController::class, 'show'])->withTrashed()->name('products.show');
    Route::get('products/{product}/edit', [ProductController::class, 'edit'])->withTrashed()->name('products.edit');
    Route::put('products/{product}', [ProductController::class, 'update'])->withTrashed()->name('products.update');
    Route::delete('products/{product}', [ProductController::class, 'destroy'])->withTrashed()->name('products.destroy');
    Route::patch('products/{product}/restore', [ProductController::class, 'restore'])->withTrashed()->name('products.restore');
    Route::get('products/{product}/plans', [PlanController::class, 'index'])->withTrashed()->name('products.plans.index');
    Route::get('products/{product}/plans/create', [PlanController::class, 'create'])->withTrashed()->name('products.plans.create');
    Route::post('products/{product}/plans', [PlanController::class, 'store'])->withTrashed()->name('products.plans.store');
    Route::get('leads', [LeadController::class, 'index'])->name('leads.index');
    Route::get('leads/archived', [LeadController::class, 'archived'])->name('leads.archived');
    Route::get('leads/create', [LeadController::class, 'create'])->name('leads.create');
    Route::get('leads/export', [DataExportController::class, 'leads'])->name('leads.export');
    Route::post('leads', [LeadController::class, 'store'])->name('leads.store');
    Route::get('leads/{lead}', [LeadController::class, 'show'])->withTrashed()->name('leads.show');
    Route::get('leads/{lead}/edit', [LeadController::class, 'edit'])->withTrashed()->name('leads.edit');
    Route::put('leads/{lead}', [LeadController::class, 'update'])->withTrashed()->name('leads.update');
    Route::post('leads/{lead}/convert', [LeadController::class, 'convert'])->name('leads.convert');
    Route::delete('leads/{lead}', [LeadController::class, 'destroy'])->withTrashed()->name('leads.destroy');
    Route::patch('leads/{lead}/restore', [LeadController::class, 'restore'])->withTrashed()->name('leads.restore');
    Route::patch('leads/{lead}/status', [LeadController::class, 'updateStatus'])->name('leads.status');
    Route::get('lead-statuses', [LeadStatusController::class, 'index'])->name('lead-statuses.index');
    Route::post('lead-statuses', [LeadStatusController::class, 'store'])->name('lead-statuses.store');
    Route::put('lead-statuses/{leadStatus}', [LeadStatusController::class, 'update'])->name('lead-statuses.update');
    Route::patch('lead-statuses/{leadStatus}/toggle', [LeadStatusController::class, 'toggle'])->name('lead-statuses.toggle');
    Route::delete('lead-statuses/{leadStatus}', [LeadStatusController::class, 'destroy'])->name('lead-statuses.destroy');
    Route::get('lead-sources', [LeadSourceController::class, 'index'])->name('lead-sources.index');
    Route::post('lead-sources', [LeadSourceController::class, 'store'])->name('lead-sources.store');
    Route::put('lead-sources/{leadSource}', [LeadSourceController::class, 'update'])->name('lead-sources.update');
    Route::patch('lead-sources/{leadSource}/toggle', [LeadSourceController::class, 'toggle'])->name('lead-sources.toggle');
    Route::delete('lead-sources/{leadSource}', [LeadSourceController::class, 'destroy'])->name('lead-sources.destroy');
    Route::get('follow-ups', [FollowUpController::class, 'index'])->name('follow-ups.index');
    Route::get('follow-ups/create', [FollowUpController::class, 'create'])->name('follow-ups.create');
    Route::post('follow-ups', [FollowUpController::class, 'store'])->name('follow-ups.store');
    Route::get('follow-ups/{followUp}/edit', [FollowUpController::class, 'edit'])->name('follow-ups.edit');
    Route::put('follow-ups/{followUp}', [FollowUpController::class, 'update'])->name('follow-ups.update');
    Route::patch('follow-ups/{followUp}/complete', [FollowUpController::class, 'complete'])->name('follow-ups.complete');
    Route::patch('follow-ups/{followUp}/cancel', [FollowUpController::class, 'cancel'])->name('follow-ups.cancel');
    Route::delete('follow-ups/{followUp}', [FollowUpController::class, 'destroy'])->name('follow-ups.destroy');
    Route::get('deals', [DealController::class, 'index'])->name('deals.index');
    Route::get('deals/archived', [DealController::class, 'archived'])->name('deals.archived');
    Route::get('deals/create', [DealController::class, 'create'])->name('deals.create');
    Route::post('deals', [DealController::class, 'store'])->name('deals.store');
    Route::get('deals/{deal}', [DealController::class, 'show'])->withTrashed()->name('deals.show');
    Route::get('deals/{deal}/edit', [DealController::class, 'edit'])->withTrashed()->name('deals.edit');
    Route::put('deals/{deal}', [DealController::class, 'update'])->withTrashed()->name('deals.update');
    Route::patch('deals/{deal}/stage', [DealController::class, 'updateStage'])->name('deals.stage');
    Route::delete('deals/{deal}', [DealController::class, 'destroy'])->withTrashed()->name('deals.destroy');
    Route::patch('deals/{deal}/restore', [DealController::class, 'restore'])->withTrashed()->name('deals.restore');
    Route::get('deal-stages', [DealStageController::class, 'index'])->name('deal-stages.index');
    Route::post('deal-stages', [DealStageController::class, 'store'])->name('deal-stages.store');
    Route::patch('deal-stages/reorder', [DealStageController::class, 'reorder'])->name('deal-stages.reorder');
    Route::put('deal-stages/{dealStage}', [DealStageController::class, 'update'])->name('deal-stages.update');
    Route::patch('deal-stages/{dealStage}/toggle', [DealStageController::class, 'toggle'])->name('deal-stages.toggle');
    Route::delete('deal-stages/{dealStage}', [DealStageController::class, 'destroy'])->name('deal-stages.destroy');
    Route::get('customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::get('customers/archived', [CustomerController::class, 'archived'])->name('customers.archived');
    Route::get('customers/create', [CustomerController::class, 'create'])->name('customers.create');
    Route::get('customers/export', [DataExportController::class, 'customers'])->name('customers.export');
    Route::post('customers', [CustomerController::class, 'store'])->name('customers.store');
    Route::post('customers/{customer}/contacts', [CustomerContactController::class, 'store'])->name('customers.contacts.store');
    Route::put('customers/{customer}/contacts/{contact}', [CustomerContactController::class, 'update'])->name('customers.contacts.update');
    Route::delete('customers/{customer}/contacts/{contact}', [CustomerContactController::class, 'destroy'])->name('customers.contacts.destroy');
    Route::get('customers/{customer}', [CustomerController::class, 'show'])->withTrashed()->name('customers.show');
    Route::get('customers/{customer}/edit', [CustomerController::class, 'edit'])->withTrashed()->name('customers.edit');
    Route::put('customers/{customer}', [CustomerController::class, 'update'])->withTrashed()->name('customers.update');
    Route::delete('customers/{customer}', [CustomerController::class, 'destroy'])->withTrashed()->name('customers.destroy');
    Route::patch('customers/{customer}/restore', [CustomerController::class, 'restore'])->withTrashed()->name('customers.restore');
    Route::get('instances', [ApplicationInstanceController::class, 'index'])->name('instances.index');
    Route::get('instances/archived', [ApplicationInstanceController::class, 'archived'])->name('instances.archived');
    Route::get('instances/create', [ApplicationInstanceController::class, 'create'])->name('instances.create');
    Route::post('instances', [ApplicationInstanceController::class, 'store'])->name('instances.store');
    Route::get('instances/{applicationInstance}', [ApplicationInstanceController::class, 'show'])->withTrashed()->name('instances.show');
    Route::get('instances/{applicationInstance}/edit', [ApplicationInstanceController::class, 'edit'])->withTrashed()->name('instances.edit');
    Route::put('instances/{applicationInstance}', [ApplicationInstanceController::class, 'update'])->withTrashed()->name('instances.update');
    Route::delete('instances/{applicationInstance}', [ApplicationInstanceController::class, 'destroy'])->withTrashed()->name('instances.destroy');
    Route::patch('instances/{applicationInstance}/restore', [ApplicationInstanceController::class, 'restore'])->withTrashed()->name('instances.restore');
    Route::get('subscriptions', [SubscriptionController::class, 'index'])->name('subscriptions.index');
    Route::get('subscriptions/archived', [SubscriptionController::class, 'archived'])->name('subscriptions.archived');
    Route::get('subscriptions/create', [SubscriptionController::class, 'create'])->name('subscriptions.create');
    Route::post('subscriptions', [SubscriptionController::class, 'store'])->name('subscriptions.store');
    Route::get('subscriptions/{subscription}', [SubscriptionController::class, 'show'])->withTrashed()->name('subscriptions.show');
    Route::get('subscriptions/{subscription}/edit', [SubscriptionController::class, 'edit'])->withTrashed()->name('subscriptions.edit');
    Route::put('subscriptions/{subscription}', [SubscriptionController::class, 'update'])->withTrashed()->name('subscriptions.update');
    Route::patch('subscriptions/{subscription}/renew', [SubscriptionController::class, 'renew'])->withTrashed()->name('subscriptions.renew');
    Route::delete('subscriptions/{subscription}', [SubscriptionController::class, 'destroy'])->withTrashed()->name('subscriptions.destroy');
    Route::patch('subscriptions/{subscription}/restore', [SubscriptionController::class, 'restore'])->withTrashed()->name('subscriptions.restore');
    Route::get('payments', [PaymentController::class, 'index'])->name('payments.index');
    Route::get('payments/archived', [PaymentController::class, 'archived'])->name('payments.archived');
    Route::get('payments/create', [PaymentController::class, 'create'])->name('payments.create');
    Route::post('payments', [PaymentController::class, 'store'])->name('payments.store');
    Route::get('payments/{payment}', [PaymentController::class, 'show'])->withTrashed()->name('payments.show');
    Route::get('payments/{payment}/edit', [PaymentController::class, 'edit'])->withTrashed()->name('payments.edit');
    Route::put('payments/{payment}', [PaymentController::class, 'update'])->withTrashed()->name('payments.update');
    Route::patch('payments/{payment}/mark-paid', [PaymentController::class, 'markPaid'])->withTrashed()->name('payments.mark-paid');
    Route::patch('payments/{payment}/verify', [PaymentController::class, 'verify'])->withTrashed()->name('payments.verify');
    Route::delete('payments/{payment}', [PaymentController::class, 'destroy'])->withTrashed()->name('payments.destroy');
    Route::patch('payments/{payment}/restore', [PaymentController::class, 'restore'])->withTrashed()->name('payments.restore');
    Route::get('support-tickets', [SupportTicketController::class, 'index'])->name('support-tickets.index');
    Route::get('support-tickets/archived', [SupportTicketController::class, 'archived'])->name('support-tickets.archived');
    Route::get('support-tickets/create', [SupportTicketController::class, 'create'])->name('support-tickets.create');
    Route::post('support-tickets', [SupportTicketController::class, 'store'])->name('support-tickets.store');
    Route::get('support-tickets/{supportTicket}', [SupportTicketController::class, 'show'])->withTrashed()->name('support-tickets.show');
    Route::get('support-tickets/{supportTicket}/edit', [SupportTicketController::class, 'edit'])->withTrashed()->name('support-tickets.edit');
    Route::put('support-tickets/{supportTicket}', [SupportTicketController::class, 'update'])->withTrashed()->name('support-tickets.update');
    Route::patch('support-tickets/{supportTicket}/status', [SupportTicketController::class, 'updateStatus'])->withTrashed()->name('support-tickets.status');
    Route::delete('support-tickets/{supportTicket}', [SupportTicketController::class, 'destroy'])->withTrashed()->name('support-tickets.destroy');
    Route::patch('support-tickets/{supportTicket}/restore', [SupportTicketController::class, 'restore'])->withTrashed()->name('support-tickets.restore');
    Route::get('tasks', [WorkTaskController::class, 'index'])->name('tasks.index');
    Route::get('tasks/archived', [WorkTaskController::class, 'archived'])->name('tasks.archived');
    Route::get('tasks/create', [WorkTaskController::class, 'create'])->name('tasks.create');
    Route::get('tasks/export', [DataExportController::class, 'tasks'])->name('tasks.export');
    Route::post('tasks', [WorkTaskController::class, 'store'])->name('tasks.store');
    Route::get('tasks/{workTask}', [WorkTaskController::class, 'show'])->withTrashed()->name('tasks.show');
    Route::get('tasks/{workTask}/edit', [WorkTaskController::class, 'edit'])->withTrashed()->name('tasks.edit');
    Route::put('tasks/{workTask}', [WorkTaskController::class, 'update'])->withTrashed()->name('tasks.update');
    Route::patch('tasks/{workTask}/status', [WorkTaskController::class, 'updateStatus'])->withTrashed()->name('tasks.status');
    Route::delete('tasks/{workTask}', [WorkTaskController::class, 'destroy'])->withTrashed()->name('tasks.destroy');
    Route::patch('tasks/{workTask}/restore', [WorkTaskController::class, 'restore'])->withTrashed()->name('tasks.restore');
    Route::get('plans/{plan}/edit', [PlanController::class, 'edit'])->name('plans.edit');
    Route::put('plans/{plan}', [PlanController::class, 'update'])->name('plans.update');
    Route::delete('plans/{plan}', [PlanController::class, 'destroy'])->name('plans.destroy');
    Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('roles/create', [RoleController::class, 'create'])->name('roles.create');
    Route::get('roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
    Route::post('roles', [RoleController::class, 'store'])->name('roles.store');
    Route::put('roles/{role}', [RoleController::class, 'update'])->name('roles.update');
    Route::delete('roles/{role}', [RoleController::class, 'destroy'])->name('roles.destroy');
    Route::get('login-history', LoginHistoryController::class)->name('login-history.index');
    Route::get('notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::patch('notifications/{notification}/read', [NotificationController::class, 'markRead'])->name('notifications.read');
    Route::patch('notifications/read-all', [NotificationController::class, 'markAllRead'])->name('notifications.read-all');
    Route::post('users', [UserController::class, 'store'])->name('users.store');
    Route::put('users/{user}', [UserController::class, 'update'])->name('users.update');
    Route::delete('users/{user}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::put('users/{user}/password', [UserController::class, 'resetPassword'])->name('users.password');
    Route::patch('users/{user}/status', [UserController::class, 'toggleStatus'])->name('users.status');

});
