<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\LeadSourceController;
use App\Http\Controllers\LeadStatusController;
use App\Http\Controllers\FollowUpController;
use App\Http\Controllers\LoginHistoryController;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ThemeController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/users')->name('home');

Route::middleware('auth')->group(function () {
    Route::redirect('dashboard', '/users')->name('dashboard');

    Route::get('profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::post('profile', [ProfileController::class, 'update'])->name('profile.update.upload');
    Route::put('profile/password', [ProfileController::class, 'updatePassword'])->name('profile.password');
    Route::patch('theme', [ThemeController::class, 'update'])->name('theme.update');

    Route::get('users', [UserController::class, 'index'])->name('users.index');
    Route::get('products', [ProductController::class, 'index'])->name('products.index');
    Route::get('products/archived', [ProductController::class, 'archived'])->name('products.archived');
    Route::get('products/export', [ProductController::class, 'export'])->name('products.export');
    Route::get('products/create', [ProductController::class, 'create'])->name('products.create');
    Route::post('products', [ProductController::class, 'store'])->name('products.store');
    Route::post('products/import', [ProductController::class, 'import'])->name('products.import');
    Route::get('products/{product}', [ProductController::class, 'show'])->withTrashed()->name('products.show');
    Route::get('products/{product}/edit', [ProductController::class, 'edit'])->withTrashed()->name('products.edit');
    Route::put('products/{product}', [ProductController::class, 'update'])->withTrashed()->name('products.update');
    Route::delete('products/{product}', [ProductController::class, 'destroy'])->withTrashed()->name('products.destroy');
    Route::patch('products/{product}/restore', [ProductController::class, 'restore'])->withTrashed()->name('products.restore');
    Route::get('products/{product}/plans', [PlanController::class, 'index'])->withTrashed()->name('products.plans.index');
    Route::get('products/{product}/plans/create', [PlanController::class, 'create'])->withTrashed()->name('products.plans.create');
    Route::post('products/{product}/plans', [PlanController::class, 'store'])->withTrashed()->name('products.plans.store');
    Route::get('leads', [LeadController::class, 'index'])->name('leads.index');
    Route::get('leads/archived', [LeadController::class, 'archived'])->name('leads.archived');
    Route::get('leads/create', [LeadController::class, 'create'])->name('leads.create');
    Route::post('leads', [LeadController::class, 'store'])->name('leads.store');
    Route::get('leads/{lead}', [LeadController::class, 'show'])->withTrashed()->name('leads.show');
    Route::get('leads/{lead}/edit', [LeadController::class, 'edit'])->withTrashed()->name('leads.edit');
    Route::put('leads/{lead}', [LeadController::class, 'update'])->withTrashed()->name('leads.update');
    Route::post('leads/{lead}/convert', [LeadController::class, 'convert'])->name('leads.convert');
    Route::delete('leads/{lead}', [LeadController::class, 'destroy'])->withTrashed()->name('leads.destroy');
    Route::patch('leads/{lead}/restore', [LeadController::class, 'restore'])->withTrashed()->name('leads.restore');
    Route::patch('leads/{lead}/status', [LeadController::class, 'updateStatus'])->name('leads.status');
    Route::get('lead-statuses', [LeadStatusController::class, 'index'])->name('lead-statuses.index');
    Route::post('lead-statuses', [LeadStatusController::class, 'store'])->name('lead-statuses.store');
    Route::put('lead-statuses/{leadStatus}', [LeadStatusController::class, 'update'])->name('lead-statuses.update');
    Route::patch('lead-statuses/{leadStatus}/toggle', [LeadStatusController::class, 'toggle'])->name('lead-statuses.toggle');
    Route::delete('lead-statuses/{leadStatus}', [LeadStatusController::class, 'destroy'])->name('lead-statuses.destroy');
    Route::get('lead-sources', [LeadSourceController::class, 'index'])->name('lead-sources.index');
    Route::post('lead-sources', [LeadSourceController::class, 'store'])->name('lead-sources.store');
    Route::put('lead-sources/{leadSource}', [LeadSourceController::class, 'update'])->name('lead-sources.update');
    Route::patch('lead-sources/{leadSource}/toggle', [LeadSourceController::class, 'toggle'])->name('lead-sources.toggle');
    Route::delete('lead-sources/{leadSource}', [LeadSourceController::class, 'destroy'])->name('lead-sources.destroy');
    Route::get('follow-ups', [FollowUpController::class, 'index'])->name('follow-ups.index');
    Route::get('follow-ups/create', [FollowUpController::class, 'create'])->name('follow-ups.create');
    Route::post('follow-ups', [FollowUpController::class, 'store'])->name('follow-ups.store');
    Route::get('follow-ups/{followUp}/edit', [FollowUpController::class, 'edit'])->name('follow-ups.edit');
    Route::put('follow-ups/{followUp}', [FollowUpController::class, 'update'])->name('follow-ups.update');
    Route::patch('follow-ups/{followUp}/complete', [FollowUpController::class, 'complete'])->name('follow-ups.complete');
    Route::patch('follow-ups/{followUp}/cancel', [FollowUpController::class, 'cancel'])->name('follow-ups.cancel');
    Route::delete('follow-ups/{followUp}', [FollowUpController::class, 'destroy'])->name('follow-ups.destroy');
    Route::get('customers', [CustomerController::class, 'index'])->name('customers.index');
    Route::get('customers/archived', [CustomerController::class, 'archived'])->name('customers.archived');
    Route::get('customers/create', [CustomerController::class, 'create'])->name('customers.create');
    Route::post('customers', [CustomerController::class, 'store'])->name('customers.store');
    Route::get('customers/{customer}', [CustomerController::class, 'show'])->withTrashed()->name('customers.show');
    Route::get('customers/{customer}/edit', [CustomerController::class, 'edit'])->withTrashed()->name('customers.edit');
    Route::put('customers/{customer}', [CustomerController::class, 'update'])->withTrashed()->name('customers.update');
    Route::delete('customers/{customer}', [CustomerController::class, 'destroy'])->withTrashed()->name('customers.destroy');
    Route::patch('customers/{customer}/restore', [CustomerController::class, 'restore'])->withTrashed()->name('customers.restore');
    Route::get('plans/{plan}/edit', [PlanController::class, 'edit'])->name('plans.edit');
    Route::put('plans/{plan}', [PlanController::class, 'update'])->name('plans.update');
    Route::delete('plans/{plan}', [PlanController::class, 'destroy'])->name('plans.destroy');
    Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
    Route::get('roles/create', [RoleController::class, 'create'])->name('roles.create');
    Route::get('roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
    Route::post('roles', [RoleController::class, 'store'])->name('roles.store');
    Route::put('roles/{role}', [RoleController::class, 'update'])->name('roles.update');
    Route::delete('roles/{role}', [RoleController::class, 'destroy'])->name('roles.destroy');
    Route::get('login-history', LoginHistoryController::class)->name('login-history.index');
    Route::post('users', [UserController::class, 'store'])->name('users.store');
    Route::put('users/{user}', [UserController::class, 'update'])->name('users.update');
    Route::delete('users/{user}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::put('users/{user}/password', [UserController::class, 'resetPassword'])->name('users.password');
    Route::patch('users/{user}/status', [UserController::class, 'toggleStatus'])->name('users.status');

});
