import { Head, Link, router } from '@inertiajs/react';
import { ArchiveRestore, ArrowLeft, Eye } from 'lucide-react';
import { PageHeader } from '@/components/page-header';
import { Pagination } from '@/components/pagination';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';
import type { Paginated, SupportTicket } from '@/types';
export default function ArchivedTickets({ tickets }: { tickets: Paginated<SupportTicket> }) { return <AppLayout><Head title="Archived tickets" /><PageHeader title="Archived tickets" actions={<Link href="/support-tickets"><Button variant="secondary"><ArrowLeft /> Back to Tickets</Button></Link>} /><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-line bg-surface-2 text-xs uppercase tracking-wider text-ink-3"><tr><th className="px-4 py-3">Ticket</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Archived</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-line">{tickets.data.map((ticket) => <tr key={ticket.id}><td className="px-4 py-3 font-semibold text-ink">{ticket.subject}<div className="text-xs font-normal text-ink-3">{ticket.ticket_number}</div></td><td className="px-4 py-3 text-ink-2">{ticket.customer?.business || ticket.customer?.name}</td><td className="px-4 py-3 text-ink-3">{ticket.deleted_at ? new Date(ticket.deleted_at).toLocaleDateString() : '—'}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Link href={`/support-tickets/${ticket.id}`}><Button variant="ghost" size="icon" aria-label="View ticket"><Eye /></Button></Link><Button variant="ghost" size="icon" aria-label="Restore ticket" onClick={() => router.patch(`/support-tickets/${ticket.id}/restore`)}><ArchiveRestore /></Button></div></td></tr>)}</tbody></table></div><Pagination meta={tickets} perPage={tickets.per_page} /></Card></AppLayout>; }
