import { Link, useForm } from '@inertiajs/react';
import { LoaderCircle } from 'lucide-react';
import type { FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardBody, CardFooter, CardHeader } from '@/components/ui/card';
import { Field, Input, Textarea } from '@/components/ui/field';
import { SearchableSelect } from '@/components/ui/searchable-select';
import type { SupportTicket, UserRef, WorkTask } from '@/types';
type Ref = { id: number; name: string; business?: string | null; email?: string | null };
type TicketRef = Pick<SupportTicket, 'id' | 'ticket_number' | 'subject'>;
export function TaskForm({ task, customers, instances, tickets, assignees, defaultSupportTicketId, action, method, submitLabel }: { task?: WorkTask; customers: Ref[]; instances: Ref[]; tickets: TicketRef[]; assignees: UserRef[]; defaultSupportTicketId?: number | null; action: string; method: 'post' | 'put'; submitLabel: string }) {
    const { data, setData, post, put, transform, processing, errors } = useForm({ customer_id: task?.customer_id ? String(task.customer_id) : '', application_instance_id: task?.application_instance_id ? String(task.application_instance_id) : '', support_ticket_id: task?.support_ticket_id ? String(task.support_ticket_id) : defaultSupportTicketId ? String(defaultSupportTicketId) : '', assigned_to_id: task?.assigned_to_id ? String(task.assigned_to_id) : '', title: task?.title ?? '', description: task?.description ?? '', priority: task?.priority ?? 'normal', status: task?.status ?? 'open', due_at: task?.due_at?.slice(0, 10) ?? '' });
    const selectProps = (props: { id: string; 'aria-invalid': boolean; 'aria-describedby'?: string }) => ({ id: props.id, invalid: props['aria-invalid'], describedBy: props['aria-describedby'] });
    const options = (values: string[]) => values.map((value) => ({ value, label: value.replace('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()) }));
    const customerOptions = [{ value: '', label: 'No linked customer' }, ...customers.map((item) => ({ value: String(item.id), label: item.name, hint: item.business || item.email || undefined }))];
    const instanceOptions = [{ value: '', label: 'No specific instance' }, ...instances.map((item) => ({ value: String(item.id), label: item.name, hint: item.business || item.email || undefined }))];
    const ticketOptions = [{ value: '', label: 'No linked ticket' }, ...tickets.map((item) => ({ value: String(item.id), label: `${item.ticket_number} · ${item.subject}` }))];
    const assigneeOptions = [{ value: '', label: 'Unassigned' }, ...assignees.map((item) => ({ value: String(item.id), label: item.name, hint: item.email }))];
    function submit(event: FormEvent) { event.preventDefault(); transform((values) => ({ ...values, customer_id: values.customer_id ? Number(values.customer_id) : null, application_instance_id: values.application_instance_id ? Number(values.application_instance_id) : null, support_ticket_id: values.support_ticket_id ? Number(values.support_ticket_id) : null, assigned_to_id: values.assigned_to_id ? Number(values.assigned_to_id) : null })); (method === 'post' ? post : put)(action); }
    return <form onSubmit={submit} noValidate className="space-y-4"><Card><CardHeader title="Task details" /><CardBody className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Title" error={errors.title} required className="lg:col-span-2">{(props) => <Input {...props} value={data.title} onChange={(event) => setData('title', event.target.value)} placeholder="Prepare deployment checklist" />}</Field><Field label="Assignee" error={errors.assigned_to_id}>{(props) => <SearchableSelect {...selectProps(props)} options={assigneeOptions} value={data.assigned_to_id} onChange={(value) => setData('assigned_to_id', value)} placeholder="Unassigned" searchPlaceholder="Search users..." />}</Field><Field label="Due on" error={errors.due_at}>{(props) => <Input {...props} type="date" value={data.due_at} onChange={(event) => setData('due_at', event.target.value)} />}</Field><Field label="Customer" error={errors.customer_id}>{(props) => <SearchableSelect {...selectProps(props)} options={customerOptions} value={data.customer_id} onChange={(value) => setData('customer_id', value)} placeholder="No linked customer" searchPlaceholder="Search customers..." />}</Field><Field label="Application instance" error={errors.application_instance_id}>{(props) => <SearchableSelect {...selectProps(props)} options={instanceOptions} value={data.application_instance_id} onChange={(value) => setData('application_instance_id', value)} placeholder="No specific instance" searchPlaceholder="Search instances..." />}</Field><Field label="Support ticket" error={errors.support_ticket_id} className="lg:col-span-2">{(props) => <SearchableSelect {...selectProps(props)} options={ticketOptions} value={data.support_ticket_id} onChange={(value) => setData('support_ticket_id', value)} placeholder="No linked ticket" searchPlaceholder="Search tickets..." />}</Field><Field label="Priority" error={errors.priority} required>{(props) => <SearchableSelect {...selectProps(props)} options={options(['low', 'normal', 'high', 'urgent'])} value={data.priority} onChange={(value) => setData('priority', value as typeof data.priority)} />}</Field><Field label="Status" error={errors.status} required>{(props) => <SearchableSelect {...selectProps(props)} options={options(['open', 'in_progress', 'completed', 'cancelled'])} value={data.status} onChange={(value) => setData('status', value as typeof data.status)} />}</Field><Field label="Description" error={errors.description} className="sm:col-span-2 lg:col-span-4">{(props) => <Textarea {...props} rows={7} value={data.description} onChange={(event) => setData('description', event.target.value)} placeholder="Add task context and expected outcome." />}</Field></CardBody><CardFooter><Link href={task ? `/tasks/${task.id}` : '/tasks'}><Button variant="secondary">Cancel</Button></Link><Button type="submit" disabled={processing}>{processing && <LoaderCircle className="animate-spin" />}{submitLabel}</Button></CardFooter></Card></form>;
}
