<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreWorkTaskRequest;
use App\Http\Requests\UpdateWorkTaskRequest;
use App\Models\ApplicationInstance;
use App\Models\Customer;
use App\Models\SupportTicket;
use App\Models\User;
use App\Models\WorkTask;
use App\Notifications\CrmNotification;
use App\Support\Audit\ActivityLogger;
use App\Services\AssignmentRouter;
use App\Services\DemoWorkflowService;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Gate;
use Inertia\Inertia;
use Inertia\Response;

class WorkTaskController extends Controller
{
    private const SORTABLE = ['task_number', 'title', 'priority', 'status', 'due_at', 'created_at'];
    public function index(Request $request): Response { return $this->listing($request, false); }
    public function archived(Request $request): Response { return $this->listing($request, true); }
    public function create(): Response { Gate::authorize('create', WorkTask::class); return Inertia::render('tasks/create', $this->options()); }
    public function store(StoreWorkTaskRequest $request, AssignmentRouter $router): RedirectResponse { $data = $request->validated(); $data['assigned_to_id'] = $router->forTask($data)?->id; $data['task_number'] = $this->nextNumber(); $data['created_by_id'] = $request->user()->id; $task = WorkTask::create($this->timestamps($data)); $this->notifyAssignee($task, 'Task assigned', "You have been assigned {$task->task_number}: {$task->title}."); return redirect()->route('tasks.show', $task)->with('success', "Task {$task->task_number} created."); }
    public function show(Request $request, WorkTask $workTask): Response { Gate::authorize('view', $workTask); $workTask->load(['lead:id,name,business,email,customer_id', 'product:id,name,code', 'customer:id,name,business,email', 'applicationInstance:id,name,customer_id,product_id,environment,status', 'supportTicket:id,ticket_number,subject', 'assignedTo:id,name,email,avatar_path', 'createdBy:id,name,email,avatar_path']); return Inertia::render('tasks/show', ['task' => $this->payload($workTask), 'activities' => $workTask->activities()->with('user:id,name,avatar_path')->limit(20)->get(), 'can' => ['update' => $request->user()->can('update', $workTask), 'archive' => $request->user()->can('delete', $workTask)]]); }
    public function edit(WorkTask $workTask): Response { Gate::authorize('update', $workTask); return Inertia::render('tasks/edit', [...$this->options(), 'task' => $this->payload($workTask)]); }
    public function update(UpdateWorkTaskRequest $request, WorkTask $workTask, ActivityLogger $logger, DemoWorkflowService $demoWorkflow): RedirectResponse { $before = $workTask->only(['status', 'priority', 'assigned_to_id']); $workTask->update($this->timestamps($request->validated())); $after = $workTask->only(array_keys($before)); if ($before['status'] !== $after['status']) { $logger->log('task.status_changed', $workTask, 'Task status changed', ['old' => ['status' => $before['status']], 'new' => ['status' => $after['status']]]); $this->notifyAssignee($workTask, 'Task status updated', "{$workTask->task_number} is now ".Str::headline($workTask->status).'.'); if ($after['status'] === 'completed') $demoWorkflow->completeDemoTask($workTask->fresh(), $request->user(), $logger); } if ($before['assigned_to_id'] !== $after['assigned_to_id']) { $logger->log('task.assigned', $workTask, 'Task assignment changed'); $this->notifyAssignee($workTask, 'Task assigned', "You have been assigned {$workTask->task_number}: {$workTask->title}."); } return redirect()->route('tasks.show', $workTask)->with('success', 'Task updated.'); }
    public function updateStatus(Request $request, WorkTask $workTask, ActivityLogger $logger, DemoWorkflowService $demoWorkflow): RedirectResponse { Gate::authorize('update', $workTask); $status = $request->validate(['status' => ['required', \Illuminate\Validation\Rule::in(WorkTask::STATUSES)]])['status']; $old = $workTask->status; $workTask->update($this->timestamps(['status' => $status])); if ($old !== $status) { $logger->log('task.status_changed', $workTask, 'Task status changed', ['old' => ['status' => $old], 'new' => ['status' => $status]]); $this->notifyAssignee($workTask, 'Task status updated', "{$workTask->task_number} is now ".Str::headline($status).'.'); if ($status === 'completed') $demoWorkflow->completeDemoTask($workTask->fresh(), $request->user(), $logger); } return back()->with('success', 'Task status updated.'); }
    public function destroy(WorkTask $workTask): RedirectResponse { Gate::authorize('delete', $workTask); $workTask->delete(); return redirect()->route('tasks.index')->with('success', "Task {$workTask->task_number} archived."); }
    public function restore(WorkTask $workTask): RedirectResponse { Gate::authorize('restore', $workTask); $workTask->restore(); return redirect()->route('tasks.show', $workTask)->with('success', 'Task restored.'); }
    private function listing(Request $request, bool $archived): Response { Gate::authorize('viewAny', WorkTask::class); $requestedSort = $request->string('sort', 'created_at')->toString(); $sort = in_array($requestedSort, self::SORTABLE, true) ? $requestedSort : 'created_at'; $direction = $request->string('direction', 'desc')->toString() === 'asc' ? 'asc' : 'desc'; $perPage = in_array($request->integer('per_page', 12), [12, 25, 50, 100], true) ? $request->integer('per_page', 12) : 12; $query = WorkTask::query()->with(['customer:id,name,business', 'applicationInstance:id,name,customer_id', 'supportTicket:id,ticket_number,subject', 'assignedTo:id,name,avatar_path'])->search($request->string('search')->toString()); $query->when($archived, fn (Builder $q) => $q->onlyTrashed()); $query->when(! $archived && in_array($request->string('status')->toString(), WorkTask::STATUSES, true), fn (Builder $q) => $q->where('status', $request->string('status')->toString())); $query->when(! $archived && in_array($request->string('priority')->toString(), WorkTask::PRIORITIES, true), fn (Builder $q) => $q->where('priority', $request->string('priority')->toString())); $query->when($request->filled('assigned_to_id'), fn (Builder $q) => $q->where('assigned_to_id', $request->integer('assigned_to_id'))); $tasks = $query->orderByRaw("CASE WHEN status IN ('open','in_progress') AND due_at < ? THEN 0 ELSE 1 END", [today()])->orderBy($sort, $direction)->paginate($perPage)->withQueryString(); $stats = collect(WorkTask::STATUSES)->mapWithKeys(fn (string $status) => [$status => WorkTask::query()->where('status', $status)->count()]); return Inertia::render($archived ? 'tasks/archived' : 'tasks/index', ['tasks' => $tasks, 'filters' => ['search' => $request->string('search')->toString(), 'status' => $request->string('status')->toString(), 'priority' => $request->string('priority')->toString(), 'assigned_to_id' => $request->integer('assigned_to_id') ?: null, 'sort' => $sort, 'direction' => $direction, 'per_page' => $perPage], 'stats' => $archived ? null : $stats, 'options' => ['assignees' => $this->assignees()]]); }
    private function options(): array { return ['customers' => Customer::query()->orderBy('name')->get(['id', 'name', 'business', 'email']), 'instances' => ApplicationInstance::query()->with(['customer:id,name,business'])->where('status', '!=', 'retired')->orderBy('name')->get(['id', 'name', 'customer_id', 'environment', 'status']), 'tickets' => SupportTicket::query()->whereNull('deleted_at')->latest()->limit(500)->get(['id', 'ticket_number', 'subject']), 'assignees' => $this->assignees()]; }
    private function assignees(): Collection { return User::query()->active()->orderBy('name')->get(['id', 'name', 'email', 'avatar_path']); }
    private function nextNumber(): string { return 'TSK-'.now()->format('Y').'-'.str_pad((string) (WorkTask::withTrashed()->max('id') + 1), 5, '0', STR_PAD_LEFT); }
    private function timestamps(array $data): array { if (($data['status'] ?? null) === 'completed' && ! isset($data['completed_at'])) $data['completed_at'] = now(); if (isset($data['status']) && $data['status'] !== 'completed') $data['completed_at'] = null; return $data; }
    private function notifyAssignee(WorkTask $task, string $title, string $message): void { if (! $task->assigned_to_id) return; $assignee = User::query()->find($task->assigned_to_id); $assignee?->notify(new CrmNotification($title, $message, 'info', "/tasks/{$task->id}")); }
    private function payload(WorkTask $task): array { return [...$task->toArray(), 'status_label' => Str::headline($task->status), 'priority_label' => Str::headline($task->priority), 'is_overdue' => $task->isOverdue(), 'lead' => $task->lead, 'product' => $task->product, 'customer' => $task->customer, 'application_instance' => $task->applicationInstance, 'support_ticket' => $task->supportTicket, 'assigned_to' => $task->assignedTo ? [...$task->assignedTo->toArray(), 'avatar_url' => $task->assignedTo->avatar_url] : null]; }
}
